spring:
  datasource:
    url: jdbc:postgresql://mydb-inclass.cmpzxiqqdpxe.us-east-2.rds.amazonaws.com:5432/dbhello
    username: emily_vong
    password: [removed]
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update #was create
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
